### ISSUE TITLE
error when initializing plugin

### ISSUE THREAD

**Issue by cstmgl** [diffplug/spotless-changelog#41]
hi All,

I only learned about this gradle plugin today and looks interesting to me.
I was trying it out locally and it works perfectly, but when I run it in jenkins I'm getting this error:

```
Script '/data/jenkins_remote/workspace/t-kafka-connect-utilities_master/gradle/release.gradle' line: 19
Could not initialize class org.eclipse.jgit.transport.SshSessionFactory
```

Which is where I initialize the plugin.
I would like to know if this Ssh factory is really inherited by this plugin? Is there a way to disable this?
I honestly don't need any of the features of the git management, because I have other plugins that do that, but I was curious.
I'm mainly interested in the validation by "changelogCheck"

**Comment by nedtwigg** [comment]
My first guess is that Jenkins is using an `ssh` URL to checkout the project, and somehow something is missing for that.

Try adding a `--stacktrace` and I bet we can figure it out.

**Comment by cstmgl** [comment]
trying to reproduce the issue, it seems to only happen when I'm doing a release (in which I use another gradle task that uses git)
I also use another plugin that allows me to do that, but the error comes when it gets instanciated.
I removed the plugin now, to do a release and I'll include it again to see if I can get more details from the log.

the other plugin I also use:
    id 'org.ajoberstar.grgit' version '5.0.0'

**Comment by cstmgl** [comment]
ok got the feedback but honestly no idea how this links to this plugin :/

the error is kind of obvious `23:49:47  Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.transport.SshSessionFactory`  but honestly nothing in the stacktrace seems to point to calls from this plugin or it's packages so I'm very confused.
I only know that the "release.gradle" is indeed when the ggrit plugin is used, but if I remove this plugin then it works again... strange.
maybe "org.ajoberstar.grgit" and this plugin just don't play nice together.

```
23:49:11  + ./gradlew updateChangeLog -Pchangelog.update=true -Pversion.set=1.0.9 --stacktrace
23:49:11  Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/tmp
23:49:15  To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
23:49:20  Daemon will be stopped at the end of the build 
23:49:42  
23:49:42  > Configure project :
23:49:42  Graceful failure of remote call exception: java.lang.ExceptionInInitializerError
23:49:47  
23:49:47  > Task :updateChangeLog FAILED
23:49:47  Changelog entry added: 1.0.9
23:49:47  
23:49:47  FAILURE: Build failed with an exception.
23:49:47  
23:49:47  * Where:
23:49:47  Script '/data/jenkins_remote/workspace/t-kafka-connect-utilities_master/gradle/release.gradle' line: 19
23:49:47  
23:49:47  * What went wrong:
23:49:47  Execution failed for task ':updateChangeLog'.
23:49:47  > Could not initialize class org.eclipse.jgit.transport.SshSessionFactory
23:49:47  
23:49:47  * Try:
23:49:47  > Run with --info or --debug option to get more log output.
23:49:47  > Run with --scan to get full insights.
23:49:47  
23:49:47  * Exception is:
23:49:47  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':updateChangeLog'.
23:49:47  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
23:49:47  	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
23:49:47  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
23:49:47  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
23:49:47  	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
23:49:47  	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
23:49:47  	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
23:49:47  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
23:49:47  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
23:49:47  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
23:49:47  	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
23:49:47  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
23:49:47  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
23:49:47  Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.transport.SshSessionFactory
23:49:47  	at org.eclipse.jgit.transport.SshTransport.<init>(SshTransport.java:48)
23:49:47  	at org.eclipse.jgit.transport.TransportGitSsh.<init>(TransportGitSsh.java:116)
23:49:47  	at org.eclipse.jgit.transport.TransportGitSsh$1.open(TransportGitSsh.java:106)
23:49:47  	at org.eclipse.jgit.transport.Transport.open(Transport.java:521)
23:49:47  	at org.eclipse.jgit.transport.Transport.openAll(Transport.java:450)
23:49:47  	at org.eclipse.jgit.transport.Transport.openAll(Transport.java:340)
23:49:47  	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:122)
23:49:47  	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:1)
23:49:47  	at java_util_concurrent_Callable$call$0.call(Unknown Source)
23:49:47  	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:82)
23:49:47  	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy)
23:49:47  	at java_util_concurrent_Callable$call.call(Unknown Source)
23:49:47  	at java_util_concurrent_Callable$call.call(Unknown Source)
23:49:47  	at org.ajoberstar.grgit.internal.OpSyntax.noArgOperation(OpSyntax.groovy:10)
23:49:47  	at org.ajoberstar.grgit.internal.OpSyntax$noArgOperation$0.callStatic(Unknown Source)
23:49:47  	at org.ajoberstar.grgit.Grgit.push(Grgit.groovy)
23:49:47  	at org.ajoberstar.grgit.Grgit$push$6.call(Unknown Source)
23:49:47  	at release_aybgsuqk63o0hbc5ibg7jl8mi$_run_closure2$_closure3.doCall(/data/jenkins_remote/workspace/t-kafka-connect-utilities_master/gradle/release.gradle:19)
23:49:47  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:49:47  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:49:47  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:49:47  	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.doExecute(AbstractTask.java:751)
23:49:47  	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.lambda$execute$0(AbstractTask.java:738)
23:49:47  	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:98)
23:49:47  	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:738)
23:49:47  	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:713)
23:49:47  	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
23:49:47  	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
23:49:47  	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
23:49:47  	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
23:49:47  	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:171)
23:49:47  	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
23:49:47  	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
23:49:47  	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
23:49:47  	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
23:49:47  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
23:49:47  	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
23:49:47  	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
23:49:47  	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
23:49:47  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
23:49:47  	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
23:49:47  	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
23:49:47  	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
23:49:47  	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
23:49:47  	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
23:49:47  	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
23:49:47  	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:61)
23:49:47  	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:42)
23:49:47  	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
23:49:47  	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
23:49:47  	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:180)
23:49:47  	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
23:49:47  	at org.gradle.internal.Either$Right.fold(Either.java:175)
23:49:47  	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
23:49:47  	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
23:49:47  	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
23:49:47  	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
23:49:47  	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
23:49:47  	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
23:49:47  	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
23:49:47  	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
23:49:47  	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
23:49:47  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
23:49:47  	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
23:49:47  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
23:49:47  	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
23:49:47  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
23:49:47  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
23:49:47  	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
23:49:47  	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
23:49:47  	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:114)
23:49:47  	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
23:49:47  	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
23:49:47  	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
23:49:47  	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:249)
23:49:47  	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
23:49:47  	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:54)
23:49:47  	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
23:49:47  	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
23:49:47  	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
23:49:47  	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
23:49:47  	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
23:49:47  	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
23:49:47  	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
23:49:47  	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
23:49:47  	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
23:49:47  	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
23:49:47  	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
23:49:47  	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
23:49:47  	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
23:49:47  	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
23:49:47  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:144)
23:49:47  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
23:49:47  	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
23:49:47  	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
23:49:47  	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
23:49:47  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
23:49:47  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
23:49:47  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
23:49:47  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
23:49:47  	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
23:49:47  	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
23:49:47  	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
23:49:47  	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
23:49:47  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
23:49:47  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
```

**Comment by cstmgl** [comment]
tried to get a bit more information from the start-up

```
23:56:07  > Configure project :
23:56:07  Evaluating root project 'kafka-connect-utilities' using build file '/data/jenkins_remote/workspace/t-kafka-connect-utilities_master/build.gradle'.
23:56:07  Compiling build file '/data/jenkins_remote/workspace/t-kafka-connect-utilities_master/build.gradle' using SubsetScriptTransformer.
23:56:07  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/com.diffplug.spotless-changelog.gradle.plugin/2.4.1/com.diffplug.spotless-changelog.gradle.plugin-2.4.1.pom to /data/gradle/.tmp/gradle_download15441367512540888242bin
23:56:07  Resource missing. [HTTP HEAD: https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/com.diffplug.spotless-changelog.gradle.plugin/2.4.1/com.diffplug.spotless-changelog.gradle.plugin-2.4.1.jar]
23:56:07  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/spotless-changelog-plugin-gradle/2.4.1/spotless-changelog-plugin-gradle-2.4.1.pom to /data/gradle/.tmp/gradle_download9163609822654308044bin
23:56:07  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/spotless-changelog-plugin-gradle/2.4.1/spotless-changelog-plugin-gradle-2.4.1.module to /data/gradle/.tmp/gradle_download3963509326185339322bin
23:56:07  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/spotless-changelog-lib/2.4.1/spotless-changelog-lib-2.4.1.pom to /data/gradle/.tmp/gradle_download9201997082509979476bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/spotless-changelog-lib/2.4.1/spotless-changelog-lib-2.4.1.module to /data/gradle/.tmp/gradle_download3052561088637852585bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/durian-globals/durian-globals.dev/1.0.0/durian-globals.dev-1.0.0.pom to /data/gradle/.tmp/gradle_download13708469599633641660bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/durian-globals/durian-globals/1.0.0/durian-globals-1.0.0.pom to /data/gradle/.tmp/gradle_download16472443714375712116bin
23:56:08  Resource missing. [HTTP GET: https://gradle.sits.net/plugins/m2/com/diffplug/durian-globals/durian-globals.dev/1.0.0/durian-globals.dev-1.0.0.module]
23:56:08  Resource missing. [HTTP GET: https://gradle.sits.net/plugins/m2/com/diffplug/durian-globals/durian-globals/1.0.0/durian-globals-1.0.0.module]
23:56:08  Downloading https://gradle.sits.net/plugins/m2/org/osgi/org.osgi.framework/1.9.0/org.osgi.framework-1.9.0.pom to /data/gradle/.tmp/gradle_download15765489650159590925bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/org/eclipse/jgit/org.eclipse.jgit.ssh.jsch/5.13.1.202206130422-r/org.eclipse.jgit.ssh.jsch-5.13.1.202206130422-r.pom to /data/gradle/.tmp/gradle_download12291194807739925371bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/spotless-changelog-plugin-gradle/2.4.1/spotless-changelog-plugin-gradle-2.4.1.jar to /data/gradle/.tmp/gradle_download10992603408059221477bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/org/eclipse/jgit/org.eclipse.jgit.ssh.jsch/5.13.1.202206130422-r/org.eclipse.jgit.ssh.jsch-5.13.1.202206130422-r.jar to /data/gradle/.tmp/gradle_download17119627613601731415bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/spotless-changelog/spotless-changelog-lib/2.4.1/spotless-changelog-lib-2.4.1.jar to /data/gradle/.tmp/gradle_download14087758187731832630bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/durian-globals/durian-globals/1.0.0/durian-globals-1.0.0.jar to /data/gradle/.tmp/gradle_download5128568318269050469bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/com/diffplug/durian-globals/durian-globals.dev/1.0.0/durian-globals.dev-1.0.0.jar to /data/gradle/.tmp/gradle_download3836437711192003077bin
23:56:08  Downloading https://gradle.sits.net/plugins/m2/org/osgi/org.osgi.framework/1.9.0/org.osgi.framework-1.9.0.jar to /data/gradle/.tmp/gradle_download67370606232532192bin
23:56:11  Git repository remote call: Grgit get remote branches list
23:56:11  Graceful failure of remote call exception: java.lang.ExceptionInInitializerError
23:56:11  Version calculation strategy [VERSION_SET] with options [[:]] from [1.0.8] with commit description [v1.0.8-1-g7ab0cfe]
23:56:12  The org.ajoberstar.grgit plugin eagerly opens a Grgit instance. Use org.ajoberstar.grgit.service for better performance.
23:56:12  Compiling build file '/data/jenkins_remote/workspace/t-kafka-connect-utilities_master/build.gradle' using BuildScriptTransformer.
23:56:14  Selected primary task 'updateChangeLog' from project :
23:56:14  Tasks to be executed: [task ':updateChangeLog']
23:56:14  Tasks that were excluded: []
23:56:14  :updateChangeLog (Thread[Execution worker for ':',5,main]) started.
23:56:14  
23:56:14  > Task :updateChangeLog FAILED
23:56:14  Caching disabled for task ':updateChangeLog' because:
23:56:14    Build cache is disabled
23:56:14  Task ':updateChangeLog' is not up-to-date because:
23:56:14    Task has not declared any outputs despite executing actions.
23:56:14  Changelog entry added: 1.0.9
23:56:14  :updateChangeLog (Thread[Execution worker for ':',5,main]) completed. Took 0.422 secs.
23:56:14  Closing Git repo: /data/jenkins_remote/workspace/t-kafka-connect-utilities_master/.git
23:56:14  
23:56:14  FAILURE: Build failed with an exception.
23:56:14  
23:56:14  * Where:
23:56:14  Script '/data/jenkins_remote/workspace/t-kafka-connect-utilities_master/gradle/release.gradle' line: 19
23:56:14  
23:56:14  * What went wrong:
23:56:14  Execution failed for task ':updateChangeLog'.
23:56:14  > Could not initialize class org.eclipse.jgit.transport.SshSessionFactory
23:56:14  
23:56:14  * Try:
23:56:14  > Run with --debug option to get more log output.
23:56:14  > Run with --scan to get full insights.
```

**Comment by nedtwigg** [comment]
I'm pretty sure this is because we are on JGit 5.x, and grgit is on JGit 6.x. We are stuck on 5.x because we're stuck on Java 8, but I think it's time to bump to Java 11 anyway. Gimme a day or two and I should have a fix for ya :)

**Comment by nedtwigg** [comment]
I believe this is fixed in `3.0.1`, can you let met know if that's true?

**Comment by cstmgl** [comment]
will test it now thank you

**Comment by cstmgl** [comment]
indeed seems the problem is gone and I can now use the plugin.
thank you
